server:
  port: 8080

spring:
  data:
    mongodb:
      password: "{cipher}AQAVvUcXQcEKSQUg6BZF0yZR9xsMEoyKcVWVTGC/d4QO+yErAFoexfE2QfiEd9GXsO/fKW7nLjJdEuG7wC6QXQ7B9X+cqhdk1SiSLt/tCRhsVUSm/IsTJXzf/hm5nm/qNmc3bM+6qYbmws3Z0Y6TrKcwEq8mVXYsP6y5IY1bwTGoZm/vXegz23RHPIY4vHuzWFFXQH7VqM79LGYq+omX5pdPOcoqU+4lDixS5B8kvE2MX1NEvzB2jVXAFxqy7r06Fgl888ntFcqCe44yjzsQQit9jxsbMtrr37yFifSHSR0gsrtqqqERYaTNufHxK+cSHm1dD0YSfbyehi2jWKmUl+L39wBoAhd/ZxgwMdrmmcAwily5pIBAtwkBOJDQhPZ0w7g="
