#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      default_zone: http://${eureka.instance.hostname}:${server.port}/eureka
#  server:
#    enable-self-preservation: false

#
# Uncomment if you'd rather use multi-peer Eureka with the eureka-1 and eureka-2
# profiles below (see Listing 13.1)
#
eureka:
  client:
    service-url:
      default_zone: http://${other.eureka.host}:${other.eureka.port}/eureka
  server:
    # Uncomment this line when in production environment
    enable-self-preservation: false

---
spring:
  profiles: eureka-1
  application:
    name: eureka-1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka1.tacocloud.com

other:
  eureka:
    host: localhost
    port: 8762

---
spring:
  profiles: eureka-2
  application:
    name: eureka-2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka2.tacocloud.com

other:
  eureka:
    host: localhost
    port: 8761